baseURL = "https://gabrylimache.github.io/"
languageCode = "it-it"
title = "Things That I Love"
theme = "PaperMod"

[params]
  homeInfoParams = {Title = "Ciao! 👋", Content = "Benvenuto nel mio blog"}
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  mainSections = ["posts"]

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Chi sono"
    url = "/chi-sono/"
    weight = 2

[caches]
  [caches.images]
    dir = ':cacheDir/images'