baseURL = "https://gabrylimache.github.io/"
languageCode = "it-it"
title = "Tastierazze"
theme = "PaperMod"
mainSections = ["posts"]

[params]
  
  [params.homeInfoParams]
  Title = "Ciao! Sono Gonza"
  Content = """
  Benvenuti nel mio blog, uno spazio personale dove raccolgo appunti, riflessioni ed esperimenti in ambito musicale: suoni, patch, workflow e tutto ciò che mi aiuta a creare, ricordare e migliorare nel tempo.

  *Non sono un esperto: scrivo per imparare, sperimentare e condividere il mio percorso.*
  """
  
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  mainSections = ["posts"]
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/gabriele-gonzalo-limache-reategui-760a84313"
  [[params.socialIcons]]
    name = "instagram"
    url = "https://instagram.com/gabry_gonza"
  [[params.socialIcons]]
    name = "tiktok"
    url = "https://tiktok.com/@gabry_gonza"
  [[params.socialIcons]]
    name = "cv"
    url = "https://drive.google.com/file/d/1qLZ2NNs8JJjavq-xOL5pXpzdpJWixP58/view?usp=drive_link"



[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Chi sono"
    url = "/chi-sono/"
    weight = 2
  [[menu.main]]
    name = "Patches"
    url = "/patches/"
    weight = 3

[caches]
  [caches.images]
    dir = ':cacheDir/images'